---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4745056812-LCHsQxz1Db38GnAqQZG3YgfHexCSvuvArgxC3cs
:access_token_secret: rHY1bMTwdvk1fkbRDORbP4tlizIgiEL4QPVB5UBPfxqRt
